version: '3.1'
services:
  camundawork:
    image: camundawork:latest
    network_mode: bridge
    container_name: camundawork
    expose:
      - 9099
    ports:
      - 9099:9099
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres


  postgres:
    image: postgres:latest
    network_mode:   : postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=camundaworkflow


volumes:
  postgres-data: