version: '3.1'
services:
  camundawork:
    image: camundaworks:latest
    container_name: camundawork
    expose:
      - 8088
    ports:
      - 8088:8088
    restart: unless-stopped
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=postgres


volumes:
  postgres-data: