server:
  port: 9099

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mdptwitter20@gmail.com
    password: CamundaBoot1%
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  application:
    name: camundapostgres

  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/camundaworkflow
    username: docker
    password: docker

    
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/camundaworkflow
      username: docker
      password: docker
      driver-class-name: org.postgresql.Driver
      pool-name: CAMUNDA-HIKARI-POOL
      idle-timeout: 3000
      minimum-idle: 30
      maximum-pool-size: 10
      connection-timeout: 2000
      connection-test-query: select 1
      transaction-isolation: TRANSACTION_READ_COMMITTED

camunda:
  bpm:
    enabled: true
    admin-user:
      id: demo
      password: demo
    

