server:
  port: 8088

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mdptwitter20@gmail.com
    password: CamundaBoot1%
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  application:
    name: camundapostgres

  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-54-72-136-69.eu-west-1.compute.amazonaws.com/dftrpijg3lo516
    username: gagemxnwsjvhwj
    password: a795e8a0ee016932e68c211fda31e668ed932438d67bc9645e72b2ca9c048962

    
    hikari:
      jdbc-url: jdbc:postgresql://ec2-54-72-136-69.eu-west-1.compute.amazonaws.com/dftrpijg3lo516
      username: gagemxnwsjvhwj
      password: a795e8a0ee016932e68c211fda31e668ed932438d67bc9645e72b2ca9c048962
      driver-class-name: org.postgresql.Driver
      pool-name: CAMUNDA-HIKARI-POOL
      idle-timeout: 3000
      minimum-idle: 30
      maximum-pool-size: 10
      connection-timeout: 2000
      connection-test-query: select 1
      transaction-isolation: TRANSACTION_READ_COMMITTED

camunda:
  bpm:
    enabled: true
    admin-user:
      id: demo
      password: demo
    

